[package]
name = "madou-kr"
version = "0.1.0"
edition = "2024"
description = "Code for the Madou Monogatari I Korean patch toolchain"

[dependencies]
clap = { version = "4", features = ["derive"] }
crc32fast = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fontdue = "0.9"
m68000 = { git = "https://github.com/mcpads/retro-typed-isa.git", rev = "9b31c628465cb83a633445de7d39e985be184cb7" }
png = "0.17"
regex-lite = "0.1"
sha2 = "0.10"
